# HTTP(S) and SOCKS5 server on the same port
mixed-port: 7891

# Port of SOCKS5 proxy server on the local end
socks-port: 1080

# Transparent proxy server port for Linux and macOS
redir-port: 17891

allow-lan: true
bind-address: "*"

mode: rule
# rule / global / direct (default is rule)

log-level: silent
# info / warning / error / debug / silent

external-controller: 0.0.0.0:7892
external-ui: yacd-gh-pages
secret: ""


dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false

  # These nameservers are used to resolve the DNS nameserver hostnames below Specify IP addresses only

  default-nameserver:
    - 114.114.114.114

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com

  nameserver:
    - 114.114.114.114 # default value


proxies:

proxy-groups:

rule-providers:
  reject:
    type: file
    behavior: domain
#    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
     url: "https://raw.githubusercontent.com/chankanzu/clash_config/main/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

rules:
 - RULE-SET,reject,REJECT
#  - RULE-SET,icloud,DIRECT
#  - RULE-SET,apple,DIRECT
#  - RULE-SET,google,DIRECT
#  - RULE-SET,proxy,FuckWall
 # - RULE-SET,direct,DIRECT
#  - RULE-SET,lancidr,DIRECT,no-resolve
#  - RULE-SET,cncidr,DIRECT,no-resolve
# - MATCH,FuckWall
